# development:
#  adapter: postgresql
#  encoding: unicode
#  database: RocketElevator
#  pool: 5
#  username: postgres
#  host: localhost
#  password: Draven11!
#  port: 5432



development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: dwh_bi
  username: postgres
  password: Damacaargu1305
 
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: dwh_bi_test
  username: postgres
  password: Damacaargu1305
 
production:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_STATS_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>